name: Build LaTeX document

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Thesis.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -f -verbose
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Thesis.pdf
      - name: Send document to me
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Version ${{ env.RELEASE_VERSION }}
          document: Thesis.pdf